name = "aada_finance/loan"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Aiken contracts Aada Finance."
dependencies = [
  { name = "aiken-lang/stdlib", version = "main", source = "github" },
]
